### ISSUE TITLE
Cannot Find resource openCadsystem-master

### ISSUE THREAD

**Issue by XBVY** [ossified/openCad#37]
When I placed it in my server, it cannot find the resource. I configured the connections, and ran the tables, I did notice there is no resource.lua, but I'm not sure if php needs __resource.lua. Any thing I did wrong when installing?

**Comment by ChaoticR** [comment]
The CAD system is not tied to FiveM, meaning that you'll need to install in as a web application. For that, i suggest you watch the following [video](https://www.youtube.com/watch?v=fsKUEQ8Gezk).

**Comment by ossified** [comment]
Yup, as ChaoticR mentioned, this is a standalone PHP web application, not affiliated with FiveM.
