### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Zach12344** [ossified/openCad#38]
Warning: require(openCad/HIDE/connections.php): failed to open stream: No such file or directory in /storage/ssd1/588/2487588/public_html/actions/login.php on line 5

Fatal error: require(): Failed opening required 'openCad/HIDE/connections.php' (include_path='.:/usr/share/pear:/usr/share/php') in /storage/ssd1/588/2487588/public_html/actions/login.php on line 5

**Comment by ossified** [comment]
See the Readme for installation instructions, it covers the purpose of the HIDE directory and where to specify it's location
