### ISSUE TITLE
How to add a admin.

### ISSUE THREAD

**Issue by DoJoMan18** [ossified/openCad#42]
How do I add a admin?

**Comment by phillf** [comment]
@DoJoMan18 as indicated in the README the original author has abandoned this project. I would recommend using the SQL_Initialization.sql file in my fork of this repo. The default admin in that version is admin@test.com and the password is "cad2017!" (without quotes). 

https://github.com/phillf/openCad/blob/master/HIDE/openCad_Initialization.sql

**Comment by rhys19** [comment]
says page not found with your link
